### ISSUE TITLE
object bound  calculate error

### ISSUE THREAD

**Issue by zt897571** [SolarLune/resolv#17]
https://github.com/SolarLune/resolv/blob/4f47f686683f0c58bfac255c1e8f05e1dbc3e59d/object.go#L153

position (5.5, 7.5) convert into grid index (4, 6), it should be (5,7)

```golang
// WorldToSpace converts from a world position (x, y) to a position in the Space (a grid-based position).
func (sp *Space) WorldToSpace(x, y float64) (int, int) {
	fx := int(math.Floor(x / float64(sp.CellWidth)))
	fy := int(math.Floor(y / float64(sp.CellHeight)))
	return fx, fy
}

i think it should be math.Ceil rather than math.Floor

**Comment by SolarLune** [comment]
Hello! Thanks for the issue and PR - appreciate it!

However, why do you think it should be `math.Ceil()` rather than `math.Floor()` to convert a position to a grid position? As an example, if you have a position of (5.5, 7.5) and the space's grid size is (8,8), then that position would be in the grid cell (0, 0), not (1, 1).

> position (5.5, 7.5) convert into grid index (4, 6), it should be (5,7)

In your example, what's your grid size?

**Comment by zt897571** [comment]
Thanks Reply！

**Comment by SolarLune** [comment]
> Thanks Reply！ my grid size is 1

Oh, then that also might be part of the problem. The grid size is basically how large a tile or "unit" should be in your game - setting it to 1 means the grid is basically one pixel large, so it doesn't really do anything. As an example, in Super Mario Brothers, a single tile was 16x16 large.
